### ISSUE TITLE
Floating Action Button Persists on all pages

### ISSUE THREAD

**Issue by Cmion** [zuvola/flutter_expandable_fab#3] opened 2022-07-27 11:39 UTC
I added the expandable fab to a page, with its own Scaffold widget, after the fab is rendered, every other page I navigate to still persists the fab, even though it's a different Scaffold.

**Comment by zuvola** [comment] 2022-07-28 00:06
Thank you for your report.
Since I am unable to reproduce the issue, could you please submit a minimal sample code that I can reproduce?

**Comment by banziyeoh** [comment] 2022-08-10 09:05
Steps to reproduce:
1. Create a page with scaffold
2. Attach Expandable FAB to this scaffold
3. Navigate to second page via the body of the scaffold
4. In the second page, attach a default FAB to the scaffold?
5. The Expandable FAB from previous page is stacked above the one in the second page
![image](https://user-images.githubusercontent.com/16898843/183861881-1815f347-763e-44c8-aba6-784e9f3b49a2.png)

Hope i explained clearly.

**Comment by zuvola** [comment] 2022-08-19 00:44
Thank you for your the steps to reproduce it.
I have fixed the problem in version 1.5.0, please check it out.

Please note that `floatingActionButtonLocation` is now required.
```dart
Scaffold(
  floatingActionButtonLocation: ExpandableFab.location,
  ...
```

**Comment by SniffyMcTasty** [comment] 2022-08-19 16:39
I had the same problem and tried this fix, but now for some reason my EFAB shows on the top left like this:

![image](https://user-images.githubusercontent.com/68755892/185665188-25e1907c-6fbc-4090-b95e-4413137cc2cd.png)

When I try to remove the location attribute, it does this:

![image](https://user-images.githubusercontent.com/68755892/185665397-4dfb08cb-d5b1-4b60-8df5-d432848a0bc6.png)

Now I'm not too sure about the last one though, I feel that this because I tried to add an animation to animate its size at build time, since I want to make it disappear when clicking on certain children FABs. At first I wanted to just disable it, but I realized that it was impossible (for now).

To know what size I would need to put it at when completely built, I tried wrapping it with a Container with the "constraints" attribute set to Theme.of(context).floatingActionButtonTheme.sizeConstraints. I'm not sure if it's just the constraint that persisted even after I removed the Container, or if it's really your new implementation that's doing this, as I upgraded your package right after I tried it.

**Comment by SniffyMcTasty** [comment] 2022-08-19 16:59
Okay so little update: I removed my EFAB completely (as the cutting was not happening with normal FABs) and reverted back to 1.4.0, then came back to 1.5.0. This caused everything to go back to normal, which was nice, but then I tried adding the ExpandableFab.location as the floatingActionButtonLocation value of the Scaffold, and it ended up doing the following thing:

![image](https://user-images.githubusercontent.com/68755892/185670054-98965951-4300-403b-b6a5-fedbba421e22.png)

**Comment by SniffyMcTasty** [comment] 2022-08-19 18:35
Okay now honestly I'm not sure what's going on anymore... I removed the package and copied the content into a dart file to play with it a bit, and now for some reason it does the clipping thing at the bottom right when putting the location to ExpandableFab.location, which it didn't do before.

**Comment by zuvola** [comment] 2022-08-19 23:08
@SniffyMcTasty  Thank you for your report.
There seems to be something complicated going on...
It would be helpful if you could share the code that causes the problem.

**Comment by SniffyMcTasty** [comment] 2022-08-22 13:50
```dart
class _ContactsScreenState extends State<ContactsScreen> {
  bool _isList = false;
  Future<bool>? _data;
  bool _dataDone = false, _expandedFab = false;
  bool _deleteMode = false;
  List<Contact> _contacts = [];
  List<ContactList> _lists = [];
  ContactsController contactsController = ContactsController();
  ContactListsController contactListsController = ContactListsController();

  Future<bool> _fetchData() async {
    try {
      _contacts = await contactsController.list()
        ..sort((a, b) => (a.firstName.toLowerCase() +
                (a.lastName?.toLowerCase() ?? ''))
            .compareTo(
                b.firstName.toLowerCase() + (b.lastName?.toLowerCase() ?? '')));
      _lists = await contactListsController.list()
        ..sort((a, b) => a.name.toLowerCase().compareTo(b.name.toLowerCase()));
      setState(() => _dataDone = true);
      return true;
    } catch (e) {
      print(e);
      return false;
    }
  }

  void _triggerEFAB() {
    setState(() => _dataDone = !_dataDone);
    if (!_dataDone) {
      setState(() {
        _expandedFab = true;
      });
    } else {
      Future.delayed(kAnimationDuration + kBufferDuration,
          () => setState(() => _expandedFab = false));
    }
  }

  void _addContact(Contact contact) {
    _contacts.add(contact);
    _contacts.sort((a, b) => (a.firstName + (a.lastName ?? ''))
        .toLowerCase()
        .compareTo((b.firstName + (b.lastName ?? '')).toLowerCase()));
    setState(() {});
  }

  void _addList(ContactList list) {
    _lists.add(list);
    _lists.sort((a, b) => a.name.toLowerCase().compareTo(b.name.toLowerCase()));
    setState(() {});
  }

  void _delete(Object object) async {
    setState(() => _dataDone = false);
    await confirmDialog(
      context: context,
      title: 'Delete ${object is ContactList ? 'list?' : 'contact?'}',
      content:
          'Are you sure you want to delete <bold>${object is ContactList ? (object as ContactList).name : '${(object as Contact).firstName} ${(object as Contact).lastName}'}</bold> from your ${object is ContactList ? 'contact lists?' : 'contacts?'}',
      tags: {
        'bold': StyledTextTag(
          style: const TextStyle(
            color: kDrawerSelectedColor,
            fontWeight: FontWeight.bold,
          ),
        ),
      },
      confirmColor: Colors.red,
      onPressed: () async {
        LoadingDialog().show(context);
        try {
          object is ContactList
              ? await ContactListsController()
                  .delete(ids: [(object as ContactList).id])
              : await ContactsController()
                  .delete(ids: [(object as Contact).id]);
          if (object is ContactList) {
            setState(() => _lists.remove(object));
          } else {
            setState(() => _contacts.remove(object));
          }
          LoadingDialog().dismiss();
          Future.delayed(kBufferDuration, () => Navigator.pop(context));
        } catch (e) {
          LoadingDialog().dismiss();
          print('yolo');
          print(e);
        }
      },
    );
    setState(() => _dataDone = true);
  }

  @override
  void initState() {
    super.initState();
    _data = _fetchData();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () => logoutDialog(context),
      child: Scaffold(
        appBar: ReusableAppBar(),
        drawer: ReusableDrawer(),
        body: SafeArea(
          child: Container(
            width: double.infinity,
            padding: const EdgeInsets.all(16.0),
            child: FutureBuilder(
                future: _data,
                builder: (context, snapshot) => snapshot.hasData
                    ? _buildWidget(context)
                    : customLoadingSpinner),
          ),
        ),
        floatingActionButton: !_dataDone
            ? null
            : ExpandableFab(
                foregroundColor: kSemiDarkMenuColor,
                backgroundColor: kDrawerSelectedColor,
                closeButtonStyle: const ExpandableFabCloseButtonStyle(
                  foregroundColor: kDrawerSectionColor,
                  backgroundColor: kMenuTextColor,
                ),
                distance: 75,
                childrenOffset: const Offset(0, 0),
                initialOpen: _expandedFab,
                type: ExpandableFabType.up,
                children: [
                  FloatingActionButton(
                    onPressed: () => setState(() {
                      _deleteMode = !_deleteMode;
                      _triggerEFAB();
                    }), // TODO: implement onPressed function
                    backgroundColor: kDrawerSelectedColor,
                    foregroundColor: kSemiDarkMenuColor,
                    child: const Icon(
                      Icons.remove,
                      color: kSemiDarkMenuColor,
                    ),
                  ),
                  OpenContainer(
                    closedElevation:
                        Theme.of(context).floatingActionButtonTheme.elevation ??
                            6,
                    closedShape:
                        Theme.of(context).floatingActionButtonTheme.shape ??
                            const CircleBorder(),
                    closedColor: Colors.transparent,
                    openColor: kBackgroundColor,
                    transitionDuration: kAnimationDuration,
                    transitionType: ContainerTransitionType.fadeThrough,
                    closedBuilder: (context, openContainer) {
                      return FloatingActionButton(
                        onPressed: () {
                          _triggerEFAB();
                          openContainer();
                        },
                        backgroundColor: kDrawerSelectedColor,
                        foregroundColor: kSemiDarkMenuColor,
                        child: const Icon(
                          Icons.add,
                          color: kSemiDarkMenuColor,
                        ),
                      );
                    },
                    openBuilder: (context, callback) => _isList
                        ? AddContactListScreen(_addList)
                        : AddContactScreen(_addContact),
                    onClosed: (poppedValue) {
                      _triggerEFAB(); // Rebuild EFAB
                    },
                  ),
                  FloatingActionButton(
                    onPressed: () {}, // TODO: implement onPressed function
                    backgroundColor: kDrawerSelectedColor,
                    foregroundColor: kSemiDarkMenuColor,
                    child: const Icon(
                      Icons.search,
                      color: kSemiDarkMenuColor,
                    ),
                  ),
                ],
              ),
      ),
    );
  }

  Widget _buildWidget(BuildContext context) {...}
}
```

There are a few things happening here that are just workarounds to what should really happen. For example, I want to be able to make the `ExpandableFab` disappear on the screen the "Add" FAB child opens without having to use the `_triggerFab()` function that disables it and re-enable it (therefore losing its state in the process). This is the skeleton of the code that produces this problem, as I don't think there's any need to build the rest of the screen to reproduce it, and I didn't put the location parameter in there, since I reverted back to 1.4.0 in the meantime.

**Comment by zuvola** [comment] 2022-08-26 01:46
I don't know the details because the sample code is not workable, but if you want the button to disappear, you might try the following.
If you want to control animations and other details, we may need to create a new API.
Of course, PR is welcome.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_expandable_fab/flutter_expandable_fab.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.blue,
      ),
      home: const FirstPage(),
    );
  }
}

class FirstPage extends StatefulWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  State<FirstPage> createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  final _counter = ValueNotifier(0);
  List<Widget> _buttons = [];

  @override
  void initState() {
    _buttons = [
      FloatingActionButton.small(
        heroTag: null,
        child: const Icon(Icons.edit),
        onPressed: () {
          setState(() {
            _buttons = _buttons.sublist(1);
          });
        },
      ),
      FloatingActionButton.small(
        heroTag: null,
        child: const Icon(Icons.search),
        onPressed: () {},
      ),
      FloatingActionButton.small(
        heroTag: null,
        child: const Icon(Icons.share),
        onPressed: () {},
      ),
    ];

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            ValueListenableBuilder(
              valueListenable: _counter,
              builder: (context, counter, _) {
                return Text(
                  '$counter',
                  style: Theme.of(context).textTheme.displayMedium,
                );
              },
            ),
            ElevatedButton.icon(
              icon: const Icon(Icons.add),
              label: const Text('add'),
              onPressed: () => _counter.value++,
            ),
          ],
        ),
      ),
      floatingActionButtonLocation: ExpandableFab.location,
      floatingActionButton: AnimatedSwitcher(
        duration: const Duration(milliseconds: 400),
        child: ExpandableFab(
          key: ValueKey(_buttons),
          type: ExpandableFabType.up,
          initialOpen: _buttons.length < 3,
          overlayStyle: ExpandableFabOverlayStyle(
            color: Colors.black.withOpacity(0.5),
          ),
          children: _buttons,
        ),
      ),
    );
  }
}
```
</details>

**Comment by SniffyMcTasty** [comment] 2022-09-03 15:37
Sorry for my late reply, I haven't been able to get back to you on that. I am no longer working on the project that is using this package, but someone else will take over. I will link them this issue for when they will want to investigate further. So far, I still haven't been able to solve this problem other than with the method I mentioned before (which is a bypass of very poor design).

**Comment by zuvola** [comment] 2022-09-05 00:11
OK, I am sorry that your problem has not been resolved, but I am going to close this issue for now.
If you wish to continue the discussion, please open a new issue with a specific title.

**Closed by zuvola** 2022-09-05 00:11 UTC

**Comment by mrginpadd** [comment] 2022-11-16 02:32
> OK, I am sorry that your problem has not been resolved, but I am going to close this issue for now. If you wish to continue the discussion, please open a new issue with a specific title.

Just delete the Future.microtask in your source code then it will work slowly.

  double getOffsetX(
      ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
    // Future.microtask(() {
      this.scaffoldGeometry.value = scaffoldGeometry;
    // });
    return 0;
  }
